apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "events-app-%s%s" "dev" .Values.namespaceSuffix }}
  namespace: openshift-gitops
  labels:
    username: {{ .Values.username }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  # I was not able to make this work... so SHA256
  # ignoreDifferences:
  # - group: apps
  #   kind: Deployment
  #   jsonPointers:
  #   - .spec.template.spec.initContainers[*].image
  #   - .spec.template.spec.containers[*].image
  destination:
    namespace: {{ printf "%s%s" .Values.namespaceBase .Values.namespaceSuffix }}
    name: {{ .Values.destinationName }}
  project: gramola-project-dev
  syncPolicy:
    automated:
      selfHeal: true
  source:
    # This is not possible because plugin has been set to kustomized-helm and source.helm applies only to helm
    # helm:
    #   parameters:
    #     - name: clusterName
    #       value: {{ .Values.destinationName }}
    path: events-deployment/overlays/dev
    repoURL: "{{ .Values.baseRepoUrl }}.git"
    targetRevision: HEAD
    plugin:
      env:
        - name: DESTINATION_NAME
          value: "{{ .Values.destinationName }}"
        - name: BASE_REPO_URL
          value: "{{ .Values.baseRepoUrl }}"
        - name: NAMESPACE_SUFFIX
          value: "{{ .Values.namespaceSuffix }}"
      name: kustomized-helm