---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: events-source-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sourceWorkspaceSize }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: events-cache-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cacheWorkspaceSize }}