---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.gramolaGatewayServiceName }}-source-pvc"
  namespace: {{ printf "%s%s" .Values.cicdNamespace .Values.namespaceSuffix }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.sourceWorkspaceSize }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "{{ .Values.gramolaGatewayServiceName }}-cache-pvc"
  namespace: {{ printf "%s%s" .Values.cicdNamespace .Values.namespaceSuffix }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.cacheWorkspaceSize }}