---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pipelinesServiceAccountName }}
  namespace: {{ .Values.cicdNamespace }}
secrets:
- name: {{ .Values.gitPatSecretName }}
- name: {{ .Values.containerRegistrySecretName }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-scc-{{ .Values.pipelinesServiceAccountName }}-rolebinding
  namespace: {{ .Values.cicdNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.pipelinesServiceAccountName }}
    namespace: {{ .Values.cicdNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: openshift-pipelines-clusterinterceptors-{{ .Values.pipelinesServiceAccountName }}-clusterrolebinding
  namespace: {{ .Values.cicdNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.pipelinesServiceAccountName }}
    namespace: {{ .Values.cicdNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openshift-pipelines-clusterinterceptors
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-{{ .Values.pipelinesServiceAccountName }}-rolebinding
  namespace: {{ .Values.cicdNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.pipelinesServiceAccountName }}
    namespace: {{ .Values.cicdNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
