apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base/events

patchesStrategicMerge:
- events-debug.yaml
- events-replicas.yaml

secretGenerator:
- name: events-database-secret
  literals:
  - DB_HOST=events-database
  - DB_USER=luke
  - DB_PASSWORD=secret
  - DB_NAME=EVENTS

images:
- name: quay.io/atarazana/gramola-events:PLACEHOLDER
  newTag: 0.0.1-SNAPSHOT