kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    app.openshift.io/connects-to: >-
      ["events",{"apiVersion":"apps/v1","kind":"Deployment","name":"events"}]
    app.quarkus.io/vcs-url: '{{ .Values.baseRepoUrl }}-gateway.git'
    app.openshift.io/vcs-uri: '{{ .Values.baseRepoUrl }}-gateway.git'
    app.openshift.io/vcs-ref: ''
  name: gateway
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: gramola-app
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.openshift.io/runtime: quarkus
spec:
  strategy:
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gateway
      app.kubernetes.io/part-of: gramola-app
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      labels:
        app.kubernetes.io/name: gateway
        app.kubernetes.io/part-of: gramola-app
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
        app.openshift.io/runtime: quarkus
      annotations:
        app.openshift.io/connects-to: >-
          ["events",{"apiVersion":"apps/v1","kind":"Deployment","name":"events"}]
        app.quarkus.io/vcs-url: '{{ .Values.baseRepoUrl }}-gateway.git'
        app.openshift.io/vcs-uri: '{{ .Values.baseRepoUrl }}-gateway.git'
        app.openshift.io/vcs-ref: ''
    spec:
      containers:
        - name: gateway
          resources:
            limits:
              cpu: 500m
              memory: 250Mi
            requests:
              cpu: 200m
              memory: 150Mi
          readinessProbe:
            httpGet:
              path: /q/health/ready
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          #imagePullPolicy: IfNotPresent
          imagePullPolicy: Always
          #image: quay.io/atarazana/gramola-gateway:PLACEHOLDER
          image: gramola-gateway:0.0.0
          command:
            - java
          args:
            - '-Dquarkus.http.host=0.0.0.0'
            - '-Djava.util.logging.manager=org.jboss.logmanager.LogManager'
            - '-jar'
            - /deployments/quarkus-run.jar
      restartPolicy: Always
      terminationGracePeriodSeconds: 30