---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.buildBotServiceAccountName }}
  namespace: {{ .Values.cicdNamespace }}
secrets:
- name: {{ .Values.gitPatSecretName }}
- name: {{ .Values.containerRegistrySecretName }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pipelines-scc-{{ .Values.buildBotServiceAccountName }}-rolebinding
  namespace: {{ .Values.cicdNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.buildBotServiceAccountName }}
    namespace: {{ .Values.cicdNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-scc-clusterrole
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: edit-{{ .Values.buildBotServiceAccountName }}-rolebinding
  namespace: {{ .Values.cicdNamespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.buildBotServiceAccountName }}
    namespace: {{ .Values.cicdNamespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
