---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea-system
---
apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: repository
  namespace: gitea-system
spec:
  giteaVolumeSize: 4Gi
  giteaImageTag: latest
  postgresqlVolumeSize: 4Gi
  giteaSsl: true
  giteaAdminUser: gramola
  giteaAdminPassword: "openshift"
  giteaAdminPasswordLength: 32
  giteaAdminEmail: gramola@ocp.com
  giteaWebhookAllowedHostList: '*'
  giteaWebhookSkipTlsVerify: true
