---
apiVersion: v1
kind: Namespace
metadata:
  name: gitea-system
---
apiVersion: gpte.opentlc.com/v1
kind: Gitea
metadata:
  name: repository
  namespace: gitea-system
spec:
  giteaVolumeSize: 4Gi
  giteaImageTag: latest
  postgresqlVolumeSize: 4Gi
  giteaSsl: true
  giteaAdminUser: opentlc-mgr
  giteaAdminPassword: "r3dh4t1!"
  giteaAdminPasswordLength: "32"
  giteaAdminEmail: admin@example.com
