apiVersion: batch/v1
kind: Job
metadata:
  namespace: gitea-system
  name: gitea-setup
spec:
  backoffLimit: 10
  template:
    spec:
      containers:
      - name: worker
        image: quay.io/atarazana/gh:0.0.1
        env:
        - name: GITEA_HOST
          value: repository:3000
        - name: COUNT
          value: "99"
        - name: SLEEP_TIME
          value: "30"
        - name: PASSWORD
          value: openshift
        - name: KUBECONFIG
          value: "/tmp/config"
        - name: ADMIN_USER
          value: "gramola"
        - name: ADMIN_PASS
          value: "openshift"
        command:
        - /bin/sh
        - '-c'
        args:
        - |-
          echo "------------------------------"
          echo " Checking http://${GITEA_HOST}/"
          curl -sSf -LI http://${GITEA_HOST}/
          RET=$?
          if [ ${RET} -ne 0 ]; then
            echo "ERROR curl to GITEA_HOST=${GITEA_HOST} failed with ${RET}"
            sleep ${SLEEP_TIME}
            echo "------------------------------"
            exit ${RET}
          fi
          TOKEN_NAME="install-$RANDOM"
          GITEA_INSTALL_TOKEN=$(curl -sS -XPOST -H "Content-Type: application/json"  -k -d '{"name":"'"${TOKEN_NAME}"'"}' \
            -u ${ADMIN_USER}:${ADMIN_PASS} http://${GITEA_HOST}/api/v1/users/${ADMIN_USER}/tokens | jq -r .sha1)
          echo "GITEA_INSTALL_TOKEN=${GITEA_INSTALL_TOKEN}"
          RET=$?
          if [ -z "${GITEA_INSTALL_TOKEN}" ] || [ "${GITEA_INSTALL_TOKEN}" == "null" ]; then
            echo "ERROR no GITEA_INSTALL_TOKEN was returned, exiting with ${RET}"
            sleep ${SLEEP_TIME}
            echo "------------------------------"
            exit 1
          fi
          for i in $(seq 1 $COUNT); 
          do
            echo "Creating user${i}"
            curl -sS -X 'POST' \
              "http://${GITEA_HOST}/api/v1/admin/users?access_token=${GITEA_INSTALL_TOKEN}" \
              -H 'accept: application/json' \
              -H 'Content-Type: application/json' \
              -d '{
                    "email": "user'"${i}"'@example.com",
                    "full_name": "User user'"${i}"'",
                    "login_name": "user'"${i}"'",
                    "must_change_password": false,
                    "password": "'"${PASSWORD}"'",
                    "send_notify": true,
                    "source_id": 0,
                    "username": "user'"${i}"'",
                    "visibility" : "public"
              }'
          done
          echo "------------------------------"
        imagePullPolicy: Always
      restartPolicy: Never