apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../helm_base
namespace: gramola-dev
commonLabels:
  app.kubernetes.io/part-of: gramola-app
  app.kubernetes.io/managed-by: argocd
images:
  - name: gramola-gateway:0.0.0
    newName: quay.io/atarazana/gramola-gateway@sha256
    newTag: 585255058e9999770f76e943c2408aeaacfa293db5c7eb035f828e9ad51ce3f5
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: gateway
    path: patch/deployment_patch.yml
