apiVersion: route.openshift.io/v1
kind: Route
metadata:
  annotations:
    haproxy.router.openshift.io/timeout: 4m
    template.openshift.io/expose-uri: 'http://{.spec.host}{.spec.path}'
  name: '{{ .Values.jenkinsServiceName }}'
  namespace: '{{ .Values.jenkinsNamespace }}'
spec:
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: '{{ .Values.jenkinsServiceName }}'
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   name: '{{ .Values.jenkinsServiceName }}'
#   namespace: '{{ .Values.jenkinsNamespace }}'
#   labels:
#     app: '{{ .Values.appName }}-{{ .Values.arcoSaerServiceName }}-{{ .Values.jenkinsServiceName }}-app'
#   annotations:
#     haproxy.router.openshift.io/timeout: 4m
#     template.openshift.io/expose-uri: 'http://{.spec.host}{.spec.path}'
# spec:
#   tls:
#     insecureEdgeTerminationPolicy: Redirect
#     termination: edge
#   to:
#     kind: Service
#     name: '{{ .Values.jenkinsServiceName }}'