apiVersion: v1
kind: Namespace
metadata:
  name: {{ printf "%s%s" .Values.cicdNamespace .Values.namespaceSuffix }}
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops #argocd instance ns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"