apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "gateway-app-%s%s" "test-cloud" .Values.namespaceSuffix }}
  namespace: openshift-gitops
  labels:
    username: {{ .Values.username }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ printf "%s%s" .Values.namespaceBase .Values.namespaceSuffix }}
    name: {{ .Values.destinationName }}
  project: gramola-project-test
  syncPolicy:
    automated:
      selfHeal: true
  source:
    # This is not possible because plugin has been set to kustomized-helm and source.helm applies only to helm
    # helm:
    #   parameters:
    #     - name: clusterName
    #       value: {{ .Values.destinationName }}
    path: gateway-deployment/overlays/test-cloud
    repoURL: {{ .Values.baseRepoUrl }}
    targetRevision: HEAD
    plugin:
      env:
        - name: DESTINATION_NAME
          value: "{{ .Values.destinationName }}"
        - name: BASE_REPO_URL
          value: "{{ .Values.baseRepoUrl }}"
        - name: NAMESPACE_SUFFIX
          value: "{{ .Values.namespaceSuffix }}"
      name: kustomized-helm