apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: shared-resources-test-cloud
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  syncPolicy:
    automated: {}
  destination:
    namespace: gramola-test
    name: {{ .Values.destinationName }}
  project: gramola-project-test
  source:
    path: apps/test-cloud/shared
    repoURL: "{{ .Values.baseRepoUrl }}.git"
    targetRevision: HEAD
    