apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Values.appName }}-cicd-app"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.gramolaEventsCiPushTriggerRootName }}-github-listener"
  name: el-{{ .Values.gramolaEventsCiPushTriggerRootName }}-github-listener
  namespace: {{ printf "%s%s" .Values.cicdNamespace .Values.namespaceSuffix }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.gramolaEventsCiPushTriggerRootName }}-github-listener
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Values.appName }}-cicd-app"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.gramolaEventsCiPushTriggerRootName }}-gitea-listener"
  name: el-{{ .Values.gramolaEventsCiPushTriggerRootName }}-gitea-listener
  namespace: {{ printf "%s%s" .Values.cicdNamespace .Values.namespaceSuffix }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.gramolaEventsCiPushTriggerRootName }}-gitea-listener
    weight: 100
  wildcardPolicy: None
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/instance: "{{ .Values.appName }}-cicd-app"
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: "{{ .Values.gramolaEventsCiPushTriggerRootName }}-gitlab-listener"
  name: el-{{ .Values.gramolaEventsCiPushTriggerRootName }}-gitlab-listener
  namespace: {{ printf "%s%s" .Values.cicdNamespace .Values.namespaceSuffix }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ .Values.gramolaEventsCiPushTriggerRootName }}-gitlab-listener
    weight: 100
  wildcardPolicy: None