apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: '{{ .Values.jenkinsServiceName }}'
  namespace: '{{ .Values.jenkinsNamespace }}'
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: '{{ .Values.jenkinsStorageSize }}'
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: '{{ .Values.jenkinsServiceName }}'
#   namespace: '{{ .Values.jenkinsNamespace }}'
#   finalizers:
#     - kubernetes.io/pvc-protection
#   labels:
#     app: '{{ .Values.appName }}-{{ .Values.arcoSaerServiceName }}-{{ .Values.jenkinsServiceName }}-app'
#     template: jenkins-persistent-template
#     app.kubernetes.io/name: '{{ .Values.jenkinsServiceName }}'
#     app.kubernetes.io/part-of: '{{ .Values.appName }}'
#     app.kubernetes.io/version: '{{ $.Chart.AppVersion }}'
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: '{{ .Values.jenkinsStorageSize }}'
#   volumeMode: Filesystem