---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.jenkins: >-
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"{{ .Values.jenkinsServiceName }}"}}
  name: '{{ .Values.jenkinsServiceName }}'
  namespace: '{{ .Values.jenkinsNamespace }}'
secrets:
- name: '{{ .Values.gitPatSecretName }}'
- name: '{{ .Values.containerRegistrySecretName }}'
---
apiVersion: authorization.openshift.io/v1
groupNames: null
kind: RoleBinding
metadata:
  name: '{{ .Values.jenkinsServiceName }}_edit'
  namespace: '{{ .Values.jenkinsNamespace }}'
roleRef:
  name: edit
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.jenkinsServiceName }}'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: '{{ .Values.jenkinsServiceName }}-sync-clusterrole'
  namespace: '{{ .Values.jenkinsNamespace }}'
  labels:
    app: '{{ .Values.appName }}-{{ .Values.arcoSaerServiceName }}-{{ .Values.jenkinsServiceName }}-app'
rules:
  ##
  ## Base operator rules
  ##
  - apiGroups:
      - ""
    resources:
      - "*"
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
    verbs:
      - "*"
  - apiGroups:
      - image.openshift.io
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - build.openshift.io
    resources:
      - "*"
    verbs:
      - "*"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ .Values.jenkinsServiceName }}-sync-clusterrolebinding'
  labels:
    app: '{{ .Values.appName }}-{{ .Values.arcoSaerServiceName }}-{{ .Values.jenkinsServiceName }}-app'
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.jenkinsServiceName }}'
    namespace: '{{ .Values.jenkinsNamespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ .Values.jenkinsServiceName }}-sync-clusterrole'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: '{{ .Values.jenkinsServiceName }}-image-puller-clusterrolebinding'
subjects:
  - kind: ServiceAccount
    name: '{{ .Values.jenkinsServiceName }}'
    namespace: '{{ .Values.jenkinsNamespace }}'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:image-puller'