kind: Service
apiVersion: v1
metadata:
  name: events-database
  annotations:
    template.openshift.io/expose-service_ip_port: '{.spec.clusterIP}:{.spec.ports[?(.name=="postgresql")].port}'
  labels:
    app: events-database
    app.kubernetes.io/component: events-database
    app.kubernetes.io/instance: events-database
spec:
  ports:
    - name: postgresql
      protocol: TCP
      port: 5432
      targetPort: 5432
  selector:
    deployment: events-database
  type: ClusterIP
  sessionAffinity: None
