kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: events
  labels:
    app.kubernetes.io/name: events
    app.kubernetes.io/part-of: gramola-app
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
    app.openshift.io/runtime: quarkus
  annotations:
    template.openshift.io/expose-uri: http://{.spec.host}{.spec.path}
    app.openshift.io/connects-to: events-database
    app.openshift.io/vcs-url: 'https://github.com/atarazana/gramola-events.git'
    app.quarkus.io/vcs-url: 'https://github.com/atarazana/gramola-events.git'
  
spec:
  path: /
  to:
    kind: Service
    name: events
    weight: 100
  port:
    targetPort: 8080
  wildcardPolicy: None