kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: "{{ .Values.appName }}-xyz"
  namespace: {{ .Values.cicdNamespace }}
  labels:
    app: "{{ .Values.appName }}-xyz-app"
spec:
  lookupPolicy:
    local: false