kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: "{{ .Values.appName }}-{{ .Values.gramolaGatewayServiceName }}-app"
  namespace: {{ .Values.jenkinsNamespace }}
  labels:
    app: "{{ .Values.appName }}-{{ .Values.gramolaGatewayServiceName }}-app"
spec:
  lookupPolicy:
    local: false