appName: gramola

gitUrl: https://github.com
gitUsername: atarazana
baseRepoName: gramola
baseRepoUrl: https://github.com/atarazana/gramola

containerRegistryServer: quay.io
containerRegistryOrg: atarazana

cicdNamespace: gramola-cicd
namespaceSuffix: ""
username: ""

gitSslVerify: true

buildahBuilderImage: registry.redhat.io/rhel8/buildah@sha256:6a68ece207bc5fd8db2dd5cc2d0b53136236fb5178eb5b71eebe5d07a3c33d13

sourceWorkspaceSize: 10Gi
cacheWorkspaceSize: 10Gi

pipelinesServiceAccountName: build-bot

containerRegistrySecretName: container-registry-secret
gitPatSecretName: git-pat-secret
gitPatSecretKey: password

# Pipelines have these stages => overlays
overlays: "dev,test"

# Service names Gramola is made of services, these are their names
gramolaEventsServiceName: events
gramolaGatewayServiceName: gateway

# Overlays relative path in the config repository
gramolaEventsOverlayPath: ./events-deployment/overlays
gramolaGatewayOverlayPath: ./gateway-deployment/overlays

# Pipeline names

## These pipelines run CI tasks and are triggered by PUSH to the source code git repo
## The final task sends a PR to the config repository for the first overlay
gramolaEventsContinuosIntegrationPipeline: events-ci-pl
gramolaGatewayContinuosIntegrationPipeline: gateway-ci-pl

## These pipelines run CD tasks and are triggered by PULL REQUESTS closed and merged to the config repo
gramolaEventsContinuosDeliveryPipeline: events-cd-pl
gramolaGatewayContinuosDeliveryPipeline: gateway-cd-pl

# Pipelines triggers

## CI pipelines triggered by PUSH
gramolaEventsCiPushTriggerRootName: events-ci-pl-push
gramolaGatewayCiPushTriggerRootName: gateway-ci-pl-push

## CD pipelines triggered by PR closed and merged
gramolaEventsCdPrTriggerRootName: events-cd-pl-pr
gramolaGatewayCdPrTriggerRootName: gateway-cd-pl-pr
