apiVersion: v1
kind: Namespace
metadata:
  name: '{{ .Values.jenkinsNamespace }}'
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops #argocd instance ns
  annotations:
    argocd.argoproj.io/sync-wave: "-1"