apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.openshift.io/dependencies: '[{"name": "{{ .Values.jnlpServiceName }}", "namespace": "", "kind": "Service"}]'
    service.openshift.io/infrastructure: 'true'
  name: '{{ .Values.jenkinsServiceName }}'
  namespace: '{{ .Values.jenkinsNamespace }}'
spec:
  ports:
    - name: web
      nodePort: 0
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    name: '{{ .Values.jenkinsServiceName }}'
  sessionAffinity: None
  type: ClusterIP

# apiVersion: v1
# kind: Service
# metadata:
#   name: '{{ .Values.jenkinsServiceName }}'
#   namespace: '{{ .Values.jenkinsNamespace }}'
#   annotations:
#     service.alpha.openshift.io/dependencies: '[{"name": "{{ .Values.jnlpServiceName }}", "namespace": "", "kind": "Service"}]'
#     service.openshift.io/infrastructure: 'true'
#   labels:
#     app: '{{ .Values.appName }}-{{ .Values.arcoSaerServiceName }}-{{ .Values.jenkinsServiceName }}-app'
#     template: jenkins-persistent-template
# spec:
#   ports:
#     - name: web
#       nodePort: 0
#       port: 80
#       protocol: TCP
#       targetPort: 8080
#   selector:
#     name: '{{ .Values.jenkinsServiceName }}'
#   sessionAffinity: None
#   type: ClusterIP