apiVersion: v1
kind: Service
metadata:
  name: '{{ .Values.jnlpServiceName }}'
  namespace: '{{ .Values.jenkinsNamespace }}'
spec:
  ports:
    - name: agent
      nodePort: 0
      port: 50000
      protocol: TCP
      targetPort: 50000
  selector:
    name: '{{ .Values.jenkinsServiceName }}'
  sessionAffinity: None
  type: ClusterIP

# apiVersion: v1
# kind: Service
# metadata:
#   name: '{{ .Values.jnlpServiceName }}'
#   namespace: '{{ .Values.jenkinsNamespace }}'
#   labels:
#     app: '{{ .Values.appName }}-{{ .Values.arcoSaerServiceName }}-{{ .Values.jenkinsServiceName }}-app'
#     template: jenkins-persistent-template
# spec:
#   ports:
#     - name: agent
#       nodePort: 0
#       port: 50000
#       protocol: TCP
#       targetPort: 50000
#   selector:
#     name: '{{ .Values.jnlpServiceName }}'
#   sessionAffinity: None
#   type: ClusterIP