apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: {{ printf "%s-%s%s" .Values.rootAppNameBase "dev" .Values.namespaceSuffix }}
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    name: in-cluster
  project: default
  syncPolicy:
    automated: {}
  source:
    helm:
      parameters:
        - name: baseRepoUrl
          value: "{{ .Values.baseRepoUrl }}"
        - name: namespaceSuffix
          value: "{{ .Values.namespaceSuffix }}"
        - name: username
          value: "{{ .Values.username }}"
    path: apps/dev
    repoURL: "{{ .Values.baseRepoUrl }}.git"
    targetRevision: HEAD