apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gramola-root-app-test-roks
  namespace: openshift-gitops
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: openshift-gitops
    name: in-cluster
  project: default
  syncPolicy:
    automated: {}
  source:
    helm:
      parameters:
        - name: baseRepoUrl
          value: {{ .Values.baseRepoUrl }}
        - name: destinationName
          value: "ibm-cloud"
    path: apps/test-roks
    repoURL: {{ .Values.baseRepoUrl }}
    targetRevision: HEAD