apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: gramola-demo-policies
  namespace: rhacm-policies
spec:
  channel: rhacm-policies/gramola-demo-policies
  placement:
    local: true
  packageFilter:
    filterRef:
      name: gramola-demo-policies-github