apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../helm_base
#   - namespace.yml
namespace: gramola-test
commonLabels:
  productive-environment: "true"
  app.kubernetes.io/part-of: gramola-app
  app.kubernetes.io/managed-by: argocd
images:
  - name: gramola-gateway:0.0.0
    newName: quay.io/atarazana/gramola-gateway@sha256
    newTag: 20e768dc2287035cfd105371b47812d4f1ae3fe25ee2ad341490e190a043f9cc
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: gateway
    path: patch/deployment_patch.yml
