apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ .Values.gramolaGatewayContinuosDeliveryPipeline }}
  namespace: {{ printf "%s%s" .Values.cicdNamespace .Values.namespaceSuffix }}
  labels:
    app.kubernetes.io/instance: {{ .Values.gramolaGatewayServiceName }}
    pipeline.openshift.io/runtime: quarkus
    pipeline.openshift.io/type: knative
spec:
  params:
    - name: APP_NAME
      type: string
      default: {{ .Values.gramolaGatewayServiceName }}
    - name: GIT_REPO_CONFIG
      type: string
    - name: GIT_REVISION_CONFIG
      type: string
      default: main
    - name: IMAGE_DIGEST_CLEAN
      type: string
    - name: COUNT
      type: string
    - name: OVERLAY
      type: string
    - name: NEXT_OVERLAY
      type: string
  tasks:
    - name: argocd-sync
      params:
        - name: APP_NAME
          value: $(params.APP_NAME)-app-$(params.OVERLAY)
      taskRef:
        kind: ClusterTask
        name: argocd-sync
    - name: fetch-config-repository
      params:
        - name: url
          value: $(params.GIT_REPO_CONFIG)
        - name: revision
          value: $(params.GIT_REVISION_CONFIG)
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace-source
    - name: update-image
      when:
        - input: "$(params.NEXT_OVERLAY)"
          operator: in
          values: [{{ .Values.overlays }}]
      params:
        # - name: FILE_TO_UPDATE
        #   value: "{{ .Values.gramolaGatewayOverlayPath }}/$(params.NEXT_OVERLAY)/kustomization.yml"
        - name: OVERLAYS_PATH
          value: "{{ .Values.gramolaGatewayOverlayPath }}"
        - name: OVERLAY
          value: "$(params.NEXT_OVERLAY)"
        - name: SELECT_EXPRESSION
          value: "(.images.[] | select(.name == \"{{ .Values.appName }}-{{ .Values.gramolaGatewayServiceName }}*\")).newTag"
        - name: NEW_VALUE
          value: "$(params.IMAGE_DIGEST_CLEAN)"
      runAfter:
        - argocd-sync
        - fetch-config-repository
      taskRef:
        kind: ClusterTask
        name: yq-eval-in-place
      workspaces:
        - name: source
          workspace: workspace-source
    - name: pr-create
      when:
        - input: "$(params.NEXT_OVERLAY)"
          operator: in
          values: [{{ .Values.overlays }}]
      params:
        - name: PR_TITLE
          value: "Updating '{{ .Values.appName }}-{{ .Values.gramolaGatewayServiceName }}' image for overlay '$(params.NEXT_OVERLAY)' with new image"
        - name: PR_BODY
          value: |
            command: UPDATE_IMAGE
            serviceName: {{ .Values.gramolaGatewayServiceName }}
            count: $(params.COUNT)
            overlay: $(params.NEXT_OVERLAY)
            kustomizationPath: {{ .Values.gramolaGatewayOverlayPath }}/$(params.NEXT_OVERLAY)/kustomization.yml
            imageDigestClean: $(params.IMAGE_DIGEST_CLEAN)
            pipelineName: {{ .Values.gramolaGatewayContinuosDeliveryPipeline }}
        - name: PAT_SECRET_NAME
          value: {{ .Values.gitPatSecretName }}
        - name: PAT_SECRET_KEY
          value: {{ .Values.gitPatSecretKey }}
      runAfter:
        - update-image
      taskRef:
        kind: ClusterTask
        name: pr-create
      workspaces:
        - name: source
          workspace: workspace-source
  workspaces:
    - name: workspace-source
    - name: workspace-cache
