apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../helm_base
namespace: gramola-dev
commonLabels:
  app.kubernetes.io/part-of: gramola-app
  app.kubernetes.io/managed-by: argocd
secretGenerator:
  - name: events-database-secret
    literals:
      - DB_HOST=events-database
      - DB_USER=luke
      - DB_PASSWORD=secret
      - DB_NAME=EVENTS
# resources:
#   - namespace.yml
images:
  - name: gramola-events:0.0.0
    newName: quay.io/atarazana/gramola-events@sha256
    newTag: 6d7175af79f50f523129cd3b5c4e0aa4e8e62ca20cb638e73a66001f3b69b192
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: events
    path: patch/deployment_patch.yml
