apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../helm_base
namespace: gramola-dev
commonLabels:
  app.kubernetes.io/part-of: gramola-app
  app.kubernetes.io/managed-by: argocd
secretGenerator:
  - name: events-database-secret
    literals:
      - DB_HOST=events-database
      - DB_USER=luke
      - DB_PASSWORD=secret
      - DB_NAME=EVENTS
# resources:
#   - namespace.yml
images:
  - name: gramola-events:0.0.0
    newName: quay.io/atarazana/gramola-events@sha256
    newTag: 45637d72bc15b19bda5204e2fc807ba53c1343f1969d8b8e4e16a9d5ddf4d8d2
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: events
    path: patch/deployment_patch.yml
