apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../../helm_base
namespace: gramola-dev
commonLabels:
  app.kubernetes.io/part-of: gramola-app
  app.kubernetes.io/managed-by: argocd
secretGenerator:
  - name: events-database-secret
    literals:
      - DB_HOST=events-database
      - DB_USER=luke
      - DB_PASSWORD=secret
      - DB_NAME=EVENTS
# resources:
#   - namespace.yml
images:
  - name: gramola-events:0.0.0
    newName: quay.io/atarazana/gramola-events@sha256
    newTag: 1afd0f81fb7909de08c62df111478ac932543deb152352aac37a65a630b2ef48
patchesJson6902:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: events
    path: patch/deployment_patch.yml
